# Generated by Django 4.2.3 on 2023-07-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
